from fastapi import APIRouter, Query, Response
import httpx
from datetime import datetime
from email.utils import formatdate
import time

router = APIRouter(prefix="/mteam", tags=["mteam"])

@router.get("/rss")
async def get_mteam_rss(
    keyword: str = Query(..., description="Anime name to search"),
    publisher: str = Query("", description="Subtitle group or publisher filter"),
    api_key: str = Query(..., description="M-Team API Key")
):
    """
    Acts as an intermediate layer for M-Team.
    Searches M-Team via their API and generates an RSS 2.0 XML feed similar to Mikan.
    """
    url = "https://api.m-team.cc/api/torrent/search"
    headers = {
        "x-api-key": api_key,
        "User-Agent": "Auto_Bangumi_Proxy/1.0"
    }
    payload = {
        "mode": "normal",
        "keyword": keyword,
        "pageNumber": 1,
        "pageSize": 100,
        "visible": 1
    }

    try:
        async with httpx.AsyncClient() as client:
            resp = await client.post(url, json=payload, headers=headers, timeout=15.0)
            resp.raise_for_status()
            data = resp.json()
    except Exception as e:
        return Response(content=f"Error communicating with M-Team: {str(e)}", status_code=500)

    results = data.get("data", {}).get("data", [])
    
    # Generate RSS XML
    rss_items = []
    
    for item in results:
        name = item.get("name", "")
        # Filter by publisher if provided
        if publisher and publisher.lower() not in name.lower():
            continue
            
        tid = item.get("id", "")
        size = item.get("size", "0")
        
        # Format the pubDate to RFC-822
        created_str = item.get("createdDate")
        try:
            # Assuming M-Team returns date string like '2023-10-12 12:00:00'
            dt = datetime.strptime(created_str, "%Y-%m-%d %H:%M:%S")
            pub_date = formatdate(time.mktime(dt.timetuple()))
        except:
            pub_date = formatdate(time.time())
            
        # Download link: We encode parameters so that when AB downloads it, we can proxy the download token request.
        # But for simpler approach, M-Team might accept download with just api_key
        # Or we can just point to an intermediate download endpoint under this router
        
        # Proxy download link (must escape & as &amp; in XML attributes and tags)
        from xml.sax.saxutils import escape
        raw_dl_link = f"http://localhost:7892/api/v1/mteam/download?id={tid}&api_key={api_key}"
        dl_link = escape(raw_dl_link)
        
        rss_item = f"""
    <item>
      <title><![CDATA[{name}]]></title>
      <link>{dl_link}</link>
      <description><![CDATA[{name}]]></description>
      <pubDate>{pub_date}</pubDate>
      <enclosure url="{dl_link}" type="application/x-bittorrent" length="{size}" />
    </item>"""
        rss_items.append(rss_item)

    rss_xml = f"""<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0">
  <channel>
    <title>M-Team Proxy: {keyword}</title>
    <link>https://m-team.cc/</link>
    <description>Auto-generated by Auto_Bangumi M-Team Intermediate Layer</description>
    {''.join(rss_items)}
  </channel>
</rss>"""

    return Response(content=rss_xml, media_type="application/xml")

@router.get("/download")
async def get_mteam_download(
    id: str = Query(...),
    api_key: str = Query(...)
):
    """
    Proxy download endpoint that fetches the token and redirects to the real .torrent file.
    """
    url = f"https://api.m-team.cc/api/torrent/genDlToken?id={id}"
    headers = {
        "x-api-key": api_key,
        "User-Agent": "Auto_Bangumi_Proxy/1.0"
    }
    
    try:
        async with httpx.AsyncClient() as client:
            resp = await client.post(url, headers=headers, timeout=10.0)
            resp.raise_for_status()
            token = resp.json().get("data", "")
            
            if token:
                real_dl_link = f"https://api.m-team.cc/api/torrent/download?id={id}&token={token}"
                return Response(status_code=302, headers={"Location": real_dl_link})
            else:
                return Response("Failed to retrieve download token", status_code=400)
    except Exception as e:
        return Response(content=f"Download Error: {str(e)}", status_code=500)
